# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.
ARG AWS_ACCOUNT_ID
ARG AWS_REGION
ARG BASE_RUNTIME_IMAGE=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/aspnet-newrelic-runtime:latest

# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["FCG.Payments.API/FCG.Payments.API.csproj", "FCG.Payments.API/"]
COPY ["FCG.Payments.Application/FCG.Payments.Application.csproj", "FCG.Payments.Application/"]
COPY ["FCG.Payments.Domain/FCG.Payments.Domain.csproj", "FCG.Payments.Domain/"]
COPY ["FCG.Payments.Infra/FCG.Payments.Infra.csproj", "FCG.Payments.Infra/"]
RUN dotnet restore "./FCG.Payments.API/FCG.Payments.API.csproj"
COPY . .
WORKDIR "/src/FCG.Payments.API"
RUN dotnet build "./FCG.Payments.API.csproj" -c $BUILD_CONFIGURATION -o /app/build


# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./FCG.Paymnets.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false


# Stage final: usa a imagem do ECR com aspnet + new relic
FROM ${BASE_RUNTIME_IMAGE} AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FCG.Payments.API.dll"]