
name: Pipeline CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AZURE_CONTAINER_REGISTRY: fcgPaymentsApi
  CONTAINER_APP_NAME: fcg-payments-api
  RESOURCE_GROUP: fcgUserApi

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest
    steps:
    
      - name: Download source
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Dependency Restore
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Domain Tests
        run: dotnet test ./FCG.Payments.Domain.Tests/FCG.Payments.Domain.Tests.csproj --configuration Release --no-build --verbosity normal
  
  build-and-deploy:
    name: Deploy to Production
    needs: test
    if: success()
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FCGPAYMENTSAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FCGPAYMENTSAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FCGPAYMENTSAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fcgpaymentsapi.azurecr.io
          registryUsername: ${{ secrets.FCGPAYMENTSAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FCGPAYMENTSAPI_REGISTRY_PASSWORD }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}}
          imageToBuild: fcgpaymentsapi.azurecr.io/fcg-payments-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_